# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Andres Vilches #

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Andres Vilches 

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/andresvil10/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/_avilches
    
  - title: Nostr
    icon: nostr
    url: https://iris.to/avilches@iris.to
    
# - title: LinkedIn # Este es el nombre del botón
#   icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
#   url: https://linkedin.com/in/TU-USUARIO # Link a donde redireccionará al hacer click

# - title: Github
#   icon: github
#   url: https://github.com/TU-USUARIO

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
